trigger:
  - main

stages:
  - stage: DEV
    jobs:
      - deployment: DeployDEV
        environment: DEV
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Running DEV stage"
                - script: uname -a
                - script: echo "Completed DEV"

  - stage: UAT
    dependsOn: DEV
    jobs:
      - deployment: DeployUAT
        environment: UAT
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Running UAT stage"
                - script: uptime
                - script: echo "Completed uat"

  - stage: PROD
    dependsOn: UAT
    jobs:
      - deployment: DeployPROD
        environment: PROD
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Running PROD stage"
                - script: whoami
                - script: echo "Completed PROD"
